version: "3.9"
services:
  api:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - 8008:8000
    volumes: 
      - ${CONFIGPATH}/config/operation_config.yaml:/home/config/drivers_config.yaml
      - ${CONFIGPATH}/config/operation_config.yaml:/home/config/operation_config.yaml
    environment: 
      - DRIVERSCONFIGFILE=/home/config/drivers_config.yaml
      - OPERATIONCONFIGFILE=/home/config/operation_config.yaml
