# =================================================================
# Silicon Thermal and compressor GPIO config by evk. 
# Model
# <evk_name>:
#   com_number: <int>    # silicon thermal serial com number
#   pin_number: <int>    # gpio output pin number for compressor
# =================================================================

evk1:
  port: "/dev/ttyUSB0"
  pin_number: 31

evk2: 
  port: "/dev/ttyUSB0"
  pin_number: 33
