# =================================================================
# Silicon Thermal and compressor GPIO config by evk. 
# Model
# <evk_name>:
#   com_number: <int>    # silicon thermal serial com number
#   pin_number: <int>    # gpio output pin number for compressor
# =================================================================

evk1:
  com_number: 1
  pin_number: 31

evk2:
  com_number: 3
  pin_number: 33

evk3:
  com_number: 5
  pin_number: 35
